# Generated by Django 4.0.3 on 2025-07-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingdb',
            name='dhname',
            field=models.CharField(max_length=50, null=True, verbose_name='미용실명'),
        ),
    ]
