# Generated by Django 4.0.3 on 2025-07-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_collectingdb_dhname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingdb',
            name='cate001',
            field=models.CharField(choices=[('미용실', '미용실'), ('애견미용실', '애견미용실')], max_length=30, null=True, verbose_name='미용실/애견미용실'),
        ),
    ]
