# Generated by Django 4.0.3 on 2025-07-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_collectingdb_cate001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingdb',
            name='promoperson',
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='address001',
            field=models.CharField(max_length=100, null=True, verbose_name='주소'),
        ),
    ]
